/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gdsfeel.ide;

import com.gdsfeel.Structure;
import com.gdsfeel.ui.StructureView;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
//@ConvertAsProperties(
//        dtd = "-//com.gdsfeel.ide//Structure//EN",
//        autostore = false)
@TopComponent.Description(
        preferredID = "StructureTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
//@ActionID(category = "Window", id = "com.gdsfeel.ide.StructureTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_StructureAction",
//        preferredID = "StructureTopComponent")
@Messages({
  "CTL_StructureAction=Structure",
  "CTL_StructureTopComponent=Structure Window",
  "HINT_StructureTopComponent=This is a Structure window"
})
public final class StructureTopComponent extends TopComponent {

  private final Structure structure;

  public Structure getStructure() {
    return structure;
  }
  private StructureView structureView;

  public StructureTopComponent(Structure structure) {
    initComponents();
//    setName(Bundle.CTL_StructureTopComponent());
    setToolTipText(Bundle.HINT_StructureTopComponent());
    this.structure = structure;
    setName(this.structure.getName());
    structureView = new StructureView();
    embedPanel.add(structureView);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    embedPanel = new javax.swing.JPanel();

    embedPanel.setBackground(new java.awt.Color(204, 255, 102));
    embedPanel.setLayout(new javax.swing.BoxLayout(embedPanel, javax.swing.BoxLayout.LINE_AXIS));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(embedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(embedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel embedPanel;
  // End of variables declaration//GEN-END:variables

  @Override
  public void componentShowing() {
    structureView.setStructure(structure);
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }
}
